spring:
  datasource:
    url: jdbc:h2:mem:monnig
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
api:
  endpoint:
    base-url: /api/v1


